# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      artifact-name: tumble-yellow-dark.vsix
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        env:
          node-version: 17.x
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: |
          npm i yarn vsce -g
          yarn install
      - name: Build and package theme
        run: |
          yarn build --if-present
          vsce package --yarn -o ${{ env.artifact-name }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: extension
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.artifact-name }}
      - uses: nyaa8/package-version@v1
        with:
          path: "uwu/package.json" # Optional
          follow-symlinks: "false" # Optional
      - name: GitHub Release Action
        uses: 1fxe/GitHub-Release-Action@main
        with:
          release_token: ${{ secrets.RELEASE_TOKEN }}
          release_tag: ${{ env.PACKAGE_VERSION }}
          release_title: Tumble Yellow Dark VSCode ${{ env.PACKAGE_VERSION }}
          release_file: ${{ env.artifact-name }}
